CREATE TABLE players (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, uid TEXT, wins INTEGER, losses INTEGER, ties INTEGER, role TEXT ,numberOfLogins INTEGER, numberOfGames INTEGER, firstLogin TIMESTAMP DEFAULT CURRENT_TIMESTAMP, recentUpdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE rooms (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, roomId TEXT, numberOfPlayers INTEGER, timeCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE level1 (id INTEGER PRIMARY KEY,imageURL TEXT, name TEXT);
CREATE TABLE level2 (id INTEGER PRIMARY KEY, name TEXT, imageURL TEXT, referenceID INTEGER);
CREATE TABLE level3 (id INTEGER PRIMARY KEY, name TEXT, imageURL TEXT, referenceID INTEGER ,description TEXT);
CREATE TABLE links (id INTEGER PRIMARY KEY,referenceID INTEGER ,link TEXT);
CREATE TABLE csvs (id INTEGER PRIMARY KEY,referenceID INTEGER ,directory TEXT);


/*
links
csv files 
description
*/

INSERT INTO PLAYERS (name, uid, numberOfLogins, numberOfGames) VALUES ('test', '1', 0, 0);